'use client'
import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import ThemeModeToggle from "@/components/ThemeModeToggle";
import SideBarToggle from "@/components/SideBarToggle";
import { Provider } from "react-redux";
// import store from "reduxStore/store"
import store from "./reduxStore/store"; 
import SideBar from "@/components/SideBar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <Provider store={store}>

          {/* <ThemeProvider> */}
            {/* <ThemeModeToggle/> */}
            <SideBarToggle/>
            <SideBar/>
            {children}
          {/* </ThemeProvider> */}
        </Provider>
      </body>
    </html>
  );
}
