// 'use client'
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { ThemeProvider } from "@/components/ThemeProvider";
// import ThemeModeToggle from "@/components/ThemeModeToggle";

// import SideBarToggle from "@/components/SideBarToggle";
// import SideBar from "@/components/SideBar";


// import { Provider } from "react-redux";
// import store from "reduxStore/store"
// import store from "./reduxStore/store"; 

import "./globals.css";
// import { cookies } from "next/headers";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/AppSidebar";
import ReduxProvider from "@/components/ReduxProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
  //   title: "Create Next App",
  //   description: "Generated by create next app",
  // };
  
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <ReduxProvider>
          
          <SidebarProvider>
            <AppSidebar/>
            <main>
              <SidebarTrigger/>
              {children}
            </main>
          </SidebarProvider>

            {/* <SideBarToggle/>
            <SideBar/> */}
          {/* <ThemeProvider> */}
            {/* <ThemeModeToggle/> */}
          {/* </ThemeProvider> */}
        </ReduxProvider>
      </body>
    </html>
  );
}
